// AUTH
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

export const LOGOUT = "LOGOUT";

// BOOK SLOT
export const BOOK_SLOT = "BOOK_SLOT";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SUCCESS";
export const BOOK_SLOT_FAILED = "BOOK_SLOT_FAILED";
