// AUTH
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

export const LOGOUT = "LOGOUT";

// HOME SCREEN
export const FETCH_HOME_CONTENT = "FETCH_HOME_CONTENT";
export const FETCH_HOME_CONTENT_SUCCESS = "FETCH_HOME_CONTENT_SUCCESS";
export const FETCH_HOME_CONTENT_FAILED = "FETCH_HOME_CONTENT_FAILED";
// LOCATIONS SCREEN
export const FETCH_LOCATIONS_CONTENT = "FETCH_LOCATIONS_CONTENT";
export const FETCH_LOCATIONS_CONTENT_SUCCESS =
  "FETCH_LOCATIONS_CONTENT_SUCCESS";
export const FETCH_LOCATIONS_CONTENT_FAILED = "FETCH_LOCATIONS_CONTENT_FAILED";
// BOOK SLOT
export const BOOK_SLOT = "BOOK_SLOT";
export const BOOK_SLOT_SUCCESS = "BOOK_SLOT_SUCCESS";
export const BOOK_SLOT_FAILED = "BOOK_SLOT_FAILED";
// BLOG SCREEN
export const FETCH_BLOGS = "FETCH_BLOGS";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_FAILED = "FETCH_BLOGS_FAILED";
export const FETCH_BLOG_DETAIL = "FETCH_BLOG_DETAIL";
export const FETCH_BLOG_DETAIL_SUCCESS = "FETCH_BLOG_DETAIL_SUCCESS";
export const FETCH_BLOG_DETAIL_FAILED = "FETCH_BLOG_DETAIL_FAILED";
// CONTACT US SCREEN
export const FETCH_CONTACTUS_CONTENT = "FETCH_CONTACTUS_CONTENT";
export const FETCH_CONTACTUS_CONTENT_SUCCESS =
  "FETCH_CONTACTUS_CONTENT_SUCCESS";
export const FETCH_CONTACTUS_CONTENT_FAILED = "FETCH_CONTACTUS_CONTENT_FAILED";
export const SAVE_CONTACT_MESSAGE = "SAVE_CONTACT_MESSAGE";
export const SAVE_CONTACT_MESSAGE_SUCCESS = "SAVE_CONTACT_MESSAGE_SUCCESS";
export const SAVE_CONTACT_MESSAGE_FAILED = "SAVE_CONTACT_MESSAGE_FAILED";
// GALLERY SCREEN
export const FETCH_GALLERY_CONTENT = "FETCH_GALLERY_CONTENT";
export const FETCH_GALLERY_CONTENT_SUCCESS = "FETCH_GALLERY_CONTENT_SUCCESS";
export const FETCH_GALLERY_CONTENT_FAILED = "FETCH_GALLERY_CONTENT_FAILED";
//GENERAL
export const FORM_VALIDATIONS_ERROR = "FORM_VALIDATIONS_ERROR";
export const CLEAR_UNEXPECTED = "CLEAR_UNEXPECTED";
export const OFFLINE_ERROR = "OFFLINE_ERROR";
export const RESET_FORM_STATES = "RESET_FORM_STATES";
